### ISSUE TITLE
Visualizing the network of owner/author relationships

### ISSUE THREAD

**Issue by thegoose20** [thegoose20/modernistlibraries#5]
We'll need to use a visualization tool outside python to be able to visually explore the relationships between authors and owners.  Alternatively, we may be able to understand the relationships using NetworkX better if we graph each owner's library separately and over a specific period of time.

**Comment by QinruShi** [comment]
We can make our visualization in the website called http://vistorian.net/, which is a good way to show the connections between bookowners and bookauthors ,and the specific graph we can choose is under this link https://networkcube.github.io/networkcube/web/sites/nodelink.html?session=0&datasetName=demo_scientists

**Comment by thegoose20** [comment]
Vistorian works!  Checkout the screenshots file on the "lucy" branch.

**Comment by thegoose20** [comment]
Used Tableau for visualisation of broader views of dataset
